### PR TITLE
add support for extension methods

### PR DESCRIPTION
**Pull request by ThomasZitzler**
This adds support for extension methods to flee. 
We already use this for a long time in our project, but we are still using a fork of the VB version:
https://github.com/ThomasZitzler/flee

I would like to use that now also on .net core, so I tought switch to you version might be a good idea.
But I would need that extension support again, so I ported my VB code to C#

### CODE REVIEW

**Comment by ThomasZitzler** [comment]
@mparlak Any chance to get either this or #60 merged?

**Comment by amiqat** [comment]
Any update

**Comment by Nucs** [comment]
@amiqat see https://github.com/mparlak/Flee/pull/60

**Comment by amiqat** [comment]
i see but still i cant do extension method

**Comment by amiqat** [comment]
@ThomasZitzler @mparlak

**Comment by ThomasZitzler** [comment]
#60 was merged, so probably this one is not needed anymore

**Comment by ThomasZitzler** [comment]
@amiqat It looks to me that there is no nuget package with #60, only @mparlak can do that

**Comment by amiqat** [comment]
@ThomasZitzler thanks but the extension not work even unit test for it 
i download code from repo

**Comment by eng-marani** [comment]
I'm planning to use flee as expression evaluator. Supporting extensions would be a killer feature, but unfortunately i was not able getting it to work with latest release. It seem that #60 should address the issue, can it be incorporated into nuget package please ?
As a last resort, do anyone have created a fork containing such a feature implemented ?

**Pull request closed without merging**
